//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Stock
    {
        public int Seq { get; set; }
        public string STK { get; set; }
        public string ODNO { get; set; }
        public string IT { get; set; }
        public string PDNO { get; set; }
        public string GD { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> WGT { get; set; }
        public Nullable<decimal> ARTS { get; set; }
        public Nullable<decimal> UNPKMTWGT { get; set; }
        public string IKDAT { get; set; }
        public string DLDAT { get; set; }
        public string NRDLSHNO { get; set; }
        public string PRTMK1 { get; set; }
        public string PRTMK2 { get; set; }
        public string TXDAT { get; set; }
        public string RESMK { get; set; }
        public Nullable<decimal> ONWQTY { get; set; }
    }
}
