//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public Permissions()
        {
            this.PermissionOperations = new HashSet<PermissionOperations>();
        }
    
        public string PermissionID { get; set; }
        public string ParentID { get; set; }
        public string PermissionName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int Weight { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<PermissionOperations> PermissionOperations { get; set; }
    }
}
