//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionOperations
    {
        public PermissionOperations()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int PermissionOperationID { get; set; }
        public string PermissionID { get; set; }
        public string OperationID { get; set; }
    
        public virtual Operations Operations { get; set; }
        public virtual Permissions Permissions { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
