//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFGWarehouseSSISEntities : DbContext
    {
        public PFGWarehouseSSISEntities()
            : base("name=PFGWarehouseSSISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MIS_Stock> MIS_Stock { get; set; }
        public virtual DbSet<MIS_Stock_His> MIS_Stock_His { get; set; }
    }
}
