//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.PermissionOperations = new HashSet<PermissionOperations>();
            this.Users = new HashSet<Users>();
        }
    
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
        public string CreatorAccount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifierAccount { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<PermissionOperations> PermissionOperations { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
