//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadLog
    {
        public UploadLog()
        {
            this.UploadLogDetail = new HashSet<UploadLogDetail>();
        }
    
        public int UploadLogID { get; set; }
        public string Account { get; set; }
        public string UploadFileName { get; set; }
        public string TempFileName { get; set; }
        public System.DateTime DataUpload { get; set; }
        public int Flag { get; set; }
        public string ExceptionMessage { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public string ControllerName { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<UploadLogDetail> UploadLogDetail { get; set; }
    }
}
