//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.Inventory.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public string Account { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public string Tel { get; set; }
        public string Ext { get; set; }
        public string CreatorAccount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifierAccount { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
